<?php

 function formatSize($bytes)
    {
        $size = $bytes / 1024;
        if($size < 1024)
        {
            $size = number_format($size, 2);
            $size .= ' KB';
        }
        else
        {
            if ($size / 1024 < 1024)
            {
                $size = number_format($size / 1024, 2);
                $size .= ' MB';
            }
            else if ($size / 1024 / 1024 < 1024)
            {
                $size = number_format($size / 1024 / 1024, 2);
                $size .= ' GB';
            }
        }
        return $size;
    }


function convertS2String($time) {
  $mins = floor($time / 60);
  $secs = floatval(($time % 60) / 100);
  $time = $mins+$secs.' min.';
  return $time;

}










foreach ($this->sources as $key => $val) {
        $t = $val['Type'];
        unset($mlinkadd2);
        switch ($t)
        {
            case 1: //GNUTELLA
                $tip = "Gnutella";
                $source = "gnutella";
                $mlinkadd = "&xt=urn:sha1:".$val['Uri'];
                break;
            case 2: //ED2K
                $tip = "ED2K";
                $source = "ed2k";
                $link = "ed2k://|file|".str_replace(' ', '+', $this->file['Filename'])."|".$this->file['Size']."|".$val['Uri']."|/";
                $mlinkadd2 = "&xt=urn:ed2k:".$val['Uri'];
                break;
            case 3: // TORRENT
                $tip = "Torrent";
                $source = "torrent";
                $link = $val['Uri'];
                break;
            case 5: //TIGER HASH
                $tip = "Gnutella";
                $source = "gnutella";
                $mlinkadd = "&xt=urn:tiger:".$val['Uri'];
                break;
            case 6: //MD5 HASH
                $tip = "Gnutella";
                $source = "gnutella";
                $mlinkadd = "&xt=urn:md5:".$val['Uri'];
                break;
            case 7: //BTH HASH
                $tip = "Torrent";
                $source = "tmagnet";
                $link = "magnet:?xl=".$this->file['Size']."&dn=".str_replace(' ', '+', $this->file['Filename'])."&xt=urn:btih:".$val['Uri'];
                $mlinkadd2 = "&xt=urn:btih:".$val['Uri'];
                break;
            case 4: // JAMENDO
            case 8: // WEB
                $tip = "Web";
                $source = "web";
                $link = $val['Uri'];
                break;
            case 9: // FTP
                $tip = "FTP";
                $source = "ftp";
                $link = $val['Uri'];
                break;
            default:
                continue;
                break;
        }

        if ($source=="gnutella")
        {
            $rlink = $srcs['gnutella']['rlink'];
            if ($rlink)
                $mlink = $rlink.$mlinkadd;
            else
                $mlink = "magnet:?xl=".$this->file['Size']."&dn=".str_replace(' ', '+', $this->file['Filename']).$mlinkadd;
            $link = $mlink;
        } elseif (isset($mlinkadd2))
        {
            $srcs['gnutella']['flink'] .= $mlinkadd2;
        }

        $srcs[$source]['link'] = htmlentities($link, ENT_QUOTES, "UTF-8");
        $srcs[$source]['rlink'] = $link;
        $srcs[$source]['tip'] = $tip;
        $srcs[$source]['count'] += $val['MaxSources'];
}
foreach ($this->metadata as $key => $val)
{
    if (($val['KeyMD']=='torrent:trackers') || ($val['KeyMD']=='torrent:tracker'))
    {
        foreach (explode(' ', $val['ValueMD']) as $tr)
        {
            if ($srcs['gnutella']['link']) {
                $srcs['gnutella']['rlink'] .= '&tr='.urlencode($tr);
                $srcs['gnutella']['link'] = htmlentities($srcs['gnutella']['rlink'], ENT_QUOTES, "UTF-8");

            } else {
                $srcs['tmagnet']['rlink'] .= '&tr='.$tr;
                $srcs['tmagnet']['link'] = htmlentities($srcs['tmagnet']['rlink'], ENT_QUOTES, "UTF-8");
            }
        }
        break;
    }
}
foreach (array('w'=>'web', 'f'=>'ftp', 't'=>'torrent', 't2'=>'tmagnet', 'g'=>'gnutella', 'e'=>'ed2k') as $srci=>$srcLink)
    if (strstr($this->qs['src'], $srci[0]) && $srcs[$srcLink])
            break;

global $content;
if ($this->qs['type'])
{
    $ctype = $this->qs['type'];
} else {
    try {
        $ctype = $content['assoc'][$this->file["ContentType"]];
    } 
    catch (Exception $ex) {}
}
if (!isset($ctype)) $ctype = 'file';
$ctype = strtolower($ctype);
?>

<div id="container_search">
    <h1>
        <a href="/" ><img  src="/images/foofind_search.gif" alt="File search engine - foofind.com" title="File search engine - foofind.com" /></a>
    </h1>

    <?=$this->form; ?>
    <?if ($this->qs['q']):?>
    <div class="contentype">
        <a class="<?=(preg_match("/^$/",  $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= ''.$this->qs(array(), array('type'=>1, 'page'=>1)) ?>" ><?=$this->translate('All');?></a>
        <a class="<?=(preg_match("/^Audio$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Audio'), array('page'=>1)) ?>" ><?=$this->translate('Audio');?></a>
        <a class="<?=(preg_match("/^Video$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Video'), array('page'=>1)) ?>" ><?=$this->translate('Video');?></a>
        <a class="<?=(preg_match("/^Image$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Image'), array('page'=>1)) ?>" ><?=$this->translate('Image');?></a>
        <a class="<?=(preg_match("/^Document$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Document'), array('page'=>1)) ?>" ><?=$this->translate('Document');?></a>
        <a class="<?=(preg_match("/^Software$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Software'), array('page'=>1)) ?>" ><?=$this->translate('Software');?></a>
        <a class="<?=(preg_match("/^Archive$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Archive'), array('page'=>1)) ?>" ><?=$this->translate('Archive');?></a>
    </div>
    <?endif?>

    <hr />

    <div class="wrap_download">
    <div class="file_download">
        <h1><?=$this->file['Filename'];?></h1>

        <div class="top_download">
        <div class="download_button">
            <img alt="" src="/images/icons/content_<?=$ctype ?>.gif" /><br />
            <a title="magnet download" class="superlarge magenta awesome" href="<?=$srcs[$srcLink]['link'].$srcs[$srcLink]['flink']?>"><?=$this->translate('Download').
                
                $this->file_size   = ($this->file_size < 1) ? '' : ' ('.$this->file_size.')';?>

            </a>
         </div>

            <? //list of fields to be showed
              $whitelist = array( 'Title', 'Artist', 'Album',  'Name', 'Track', 'Genre', 'Quality', 'Files', 'Folders', 'Unpacked Size', 'Description', 'Size', 'Bitrate', 'Soundtype','Seconds', 'Minutes',
                        'Colors', 'Author', 'Format', 'Pages', 'Version', 'Codec', 'Framerate', 'Width', 'Height' );

               //list of fields to be linkable
              $linklist = array( 'Album', 'Artist', 'Title', 'Name', 'Author'  );

            ?>

       <?php if ($this->metadata):  //var_dump($ctype);
      ; ?>


            <div class="download_file_metadata"><ul>
                    <?php foreach ($this->metadata as $key => $val):

                        $val['KeyMD'] = explode(":", $val['KeyMD']);
                        $val['KeyMD'][1] = ucfirst ( $val['KeyMD'][1] );

                            if ($ctype == 'audio'){
                                   if($val['KeyMD'][1] == 'Title')  $audio['Title'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Seconds')  $audio['Seconds'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Minutes')  $audio['Minutes'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Artist')  $audio['Artist'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Album')  $audio['Album'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Year')  $audio['Year'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Track')  $audio['Track'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Genre')  $audio['Genre'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Bitrate')  $audio['Bitrate'] = $val['ValueMD'];
                                   if($val['KeyMD'][1] == 'Soundtype')  $audio['Soundtype'] = $val['ValueMD'];

                              // var_dump($audio );

                            }

                            elseif ($ctype == 'video'){
                                 if($val['KeyMD'][1] == 'Title')  $video['Title'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Seconds')  $video['Seconds'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Minutes')  $video['Minutes'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Height')  $video['Height'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Width')  $video['Width'] = $val['ValueMD'];
                            }

                            elseif ($ctype == 'archive'){
                                 if($val['KeyMD'][1] == 'Title')  $archive['Title'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Name')  $archive['Name'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Files')  $archive['Files'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Folders')  $archive['Folders'] = $val['ValueMD'];

                            }

                             elseif ($ctype == 'image'){
                                 if($val['KeyMD'][1] == 'Title')  $image['Title'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Artist')  $image['Artitst'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Description')  $image['Description'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Height')  $image['Height'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Width')  $image['Width'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Colors')  $image['Colors'] = $val['ValueMD'];
                            }

                            elseif ($ctype == 'document'){
                                 if($val['KeyMD'][1] == 'Title')  $document['Title'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Artist')  $document['Artitst'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Description')  $document['Description'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Format')  $document['Format'] = $val['ValueMD'];
                                  if($val['KeyMD'][1] == 'FormatVersion')  $document['FormatVersion'] = $val['ValueMD'];
                                 if($val['KeyMD'][1] == 'Pages')  $document['Pages'] = $val['ValueMD'];
                            }




                    ?>


                    <?php endforeach; ?>

                    <?php if($ctype == 'audio'){
                                     echo  '<li>'.$this->translate('Title').': <a href="/'.$this->lang.'/search/?q='.$audio['Title'].'">'.$audio['Title'].'</a> ('.$audio['Seconds'].')</li>';
                                     echo  '<li>'.$this->translate('Artist').': <a href="/'.$this->lang.'/search/?q='.$audio['Artist'].'">'.$audio['Artist'].'</a></li>';
                                     echo  '<li>'.$this->translate('Album').': <a href="/'.$this->lang.'/search/?q='.$audio['Album'].'">'.$audio['Album'].'</a>  ('.$audio['Year'].')</li>';
                                     echo  '<li>'.$this->translate('Track').': '.$audio['Track'].'</li>';
                                     echo  '<li>'.$this->translate('Genre').': '.$audio['Genre'].'</li>';
                                     echo  '<li>'.$this->translate('Quality').': '.$audio['Bitrate'].' kbps '.$audio['Soundtype'].'</li>';}

                               elseif($ctype == 'video'){

                                      echo  '<li>'.$this->translate('Title').': <a href="/'.$this->lang.'/search/?q='.$video['Title'].'">'.$video['Title'].'</a> ('.$video['Seconds'].')</li>';
                                      echo  '<li>'.$this->translate('Artist').': <a href="/'.$this->lang.'/search/?q='.$video['Artist'].'">'.$video['Artist'].'</a></li>';
                                      echo  '<li>'.$this->translate('Size').': '.$video['Width'].'x'.$video['Height'].'</li>';
                                      echo  '<li>'.$this->translate('Quality').': '.$video['Framerate'].' fps '.$video['Codec'].'</li>';
                                    }

                               elseif($ctype == 'archive'){
                                       echo  '<li>'.$this->translate('Title').': <a href="/'.$this->lang.'/search/?q='.$archive['Title'].'">'.$archive['Title'].'</a>  '.$archive['Name'].'</li>';
                                       echo  '<li>'.$this->translate('Files').': '.$archive['Files'].'</li>';
                                       echo  '<li>'.$this->translate('Folders').': '.$archive['Folders'].'</li>';
                                       echo  '<li>'.$this->translate('Unpacked Size').': '.$archive['Unpackedsize'].'</li>';

                                }
                               elseif($ctype == 'image'){
                                       echo  '<li>'.$this->translate('Title').': <a href="/'.$this->lang.'/search/?q='.$image['Title'].'">'.$image['Title'].'</a>  '.$image['Name'].'</li>';
                                       echo  '<li>'.$this->translate('Artist').': '.$image['Artist'].'</li>';
                                       echo  '<li>'.$this->translate('Description').': '.$image['Description'].'</li>';
                                       echo  '<li>'.$this->translate('Size').': '.$image['Height'].'x'.$image['Widht'].'</li>';
                                       echo  '<li>'.$this->translate('Colors').': '.$image['Colors'].'</li>';
                                }
                               elseif($ctype == 'document'){
                                       echo  '<li>'.$this->translate('Title').': <a href="/'.$this->lang.'/search/?q='.$document['Title'].'">'.$document['Title'].'</a></li>';
                                       echo  '<li>'.$this->translate('Author').': '.$document['Author'].'</li>';
                                       echo  '<li>'.$this->translate('Format').': '.$document['Format'].' '.$document['FormatVersion'].'</li>';
                                       echo  '<li>'.$this->translate('Pages').': '.$document['Pages'].'</li>';
                                       echo  '<li>'.$this->translate('Version').': '.$document['Version'].$document['Revision'].'</li>';
                                }

                         ?>


            </ul></div>
       <?php endif; ?>
       </div>
           


       <?php if ($this->sources): ?>
        <div class="dowload_file_sources">                
                    <? foreach ($srcs as $key => $val):
                        if ($val['link']): ?>
                        <div class="download_source" >
                            <a  title="<?=$val['link'] ?>" href="<?=$val['link'] ?>"><img alt="" src="/images/icons/<?=$key ?>_download.gif" />
                                <?='<b>'.ucfirst ( $val['tip'] ).'</b><span>'.$val['count'].' '.$this->translate('sources');?></span></a>
                                <?='<input onClick="javascript:this.focus();this.select();" type="text"  value="'.$val['link'].'" />'; ?>
                                <? unset ($type, $pinta, $link) ?>
                        </div>

                 <?php  endif;
                       endforeach; ?>

            
        </div>
       <?php endif; ?>

   <? //Zend_Debug::dump($this->file);?>
   <? //Zend_Debug::dump($this->metadata);?>
   <? //Zend_Debug::dump($this->sources);?>

        <? if ($this->lang == 'en') $langcode = 1;
             if ($this->lang == 'es') $langcode = 2;
        ?>

        <div class="sharelinks"><?=$this->translate('Share this:');?>
            <a href="http://www.facebook.com/share.php?u=http://foof.in/<?=$langcode;?>/<?=dechex($this->file['IdFile'] );?>">
                <img alt="<?=$this->translate('share on facebook');?>" src="/images/icons/ico_facebook.gif" border = "0"/></a>
                <a href="mailto:?subject=<?=$this->file['Filename'];?>&body=http://foof.in/<?=$langcode;?>/<?=dechex($this->file['IdFile']);?>">
                <img alt="<?=$this->translate('send by email');?>" src="/images/icons/ico_email_link.png" border = "0"/></a>
                <a href="http://twitter.com/home?status=http://foof.in/<?=$langcode;?>/<?=dechex($this->file['IdFile'] );?>">
                <img alt="<?=$this->translate('share on twitter');?>" src="/images/icons/ico_twitter.png" border = "0"/></a>
        </div>

    </div>


    <div class="download_more_info">
        <h3><?=$this->translate('How to download?'); ?></h3>
        <p><?=$this->translate('DownloadExplanation'); ?></p>
        <p><img title="eDonkey, eMule, MLDonkey, aMule" alt="eDonkey, eMule, MLDonkey, aMule"  src="/images/icons/ed2k.gif" /> eMule, MLDonkey, aMule.</p>
        <p><img title="Gnutella, Frostwire,Limewire, Shareaza, Phex" alt="Gnutella, Frostwire, Limewire, Shareaza, Phex"  src="/images/icons/gnutella.gif" /> Limewire, Shareaza, Phex.</p>
        <p><img title="Torrent, Vuze, µTorrent, Transmission" alt="Torrent, Vuze, µTorrent, Transmission"  src="/images/icons/torrent.gif" /> µTorrent, Transmission.</p>
    </div>


     </div>

</div>
