<div id="container_search">
    <h1>
        <a href="/" ><img  src="/images/foofind_search.gif" alt="File search engine - foofind.com" title="File search engine - foofind.com" /></a>
    </h1>

    <?=$this->form; ?>

    <div class="contentype">
        <a class="<?=(preg_match("/^$/", $_GET['type']))?"actual":""?>" href="<?= ''.$this->qs(array(), array('type'=>1, 'page'=>1)) ?>" ><?=$this->translate('All');?></a>
        <a class="<?=(preg_match("/^Audio$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Audio'), array('page'=>1)) ?>" ><?=$this->translate('Audio');?></a>
        <a class="<?=(preg_match("/^Video$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Video'), array('page'=>1)) ?>" ><?=$this->translate('Video');?></a>
        <a class="<?=(preg_match("/^Image$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Image'), array('page'=>1)) ?>" ><?=$this->translate('Image');?></a>
        <a class="<?=(preg_match("/^Document$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Document'), array('page'=>1)) ?>" ><?=$this->translate('Document');?></a>
        <a class="<?=(preg_match("/^Software$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Software'), array('page'=>1)) ?>" ><?=$this->translate('Software');?></a>
        <a class="<?=(preg_match("/^Archive$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Archive'), array('page'=>1)) ?>" ><?=$this->translate('Archive');?></a>
    </div>

    <hr />

    <div class="wrap_download">
    <div class="file_download">
        <h1><?=$this->file['Filename'];?></h1>

        <div class="top_download">
        <div class="download_button">
            <img alt="" src="/images/icons/content_<?=$this->file_content_type ?>.gif" /><br />
            <a title="magnet download" class="superlarge magenta awesome" href="/hacer_magneeeeeeet"><?=$this->translate('Download').
                
                $this->file_size   = ($this->file_size < 1) ? '' : ' ('.$this->file_size.')';?>

            </a>
         </div>

            <? //TODO use this unfonished helper
             //var_dump( $this->formatMetadata($this->metadata) );?>

       <?php if ($this->metadata): sort($this->metadata) ?>
            <div class="download_file_metadata"><ul>
                <?php foreach ($this->metadata as $key => $val): ?>


                    <? $val['KeyMD'] = explode(":", $val['KeyMD']);?>


                    <?php
                    $whitelist = array( 'Album', 'Artist', 'Title', 'Name', 'Track', 'Genre', 'Quality', 'Files', 'Folders', 'Unpacked Size', 'Description', 'Size', 'Bitrate', 'Soundtype',
                        'Colors', 'Author', 'Format', 'Pages', 'Version', 'Codec', 'Framerate', 'Width', 'Height' );

                    $val['KeyMD'][1] = ucfirst (  $this->translate($val['KeyMD'][1])  );

                    if ( in_array($val['KeyMD'][1], $whitelist ) )  : ?>
                    <?='<li>'.ucfirst (  $this->translate($val['KeyMD'][1])  ).': <a href="/'.$this->lang.'/search/?q='.$val['ValueMD'].'">'.$val['ValueMD'].'</a></li>';?>
                    <?php endif; ?>

                <?php endforeach; ?>
            </ul></div>
       <?php endif; ?>
       </div>
           




       <?php if ($this->sources): ?>
        <div class="dowload_file_sources">
                <?php foreach ($this->sources as $key => $val):  ?>

                    <?php
                    if ( $val['Type'] == 2)  { $type = 'ed2k'  ;
                                                       $urlStart = 'ed2k://|file|';
                                                       $uri = '|'.$this->file['Size'].'|'.$val['Uri'];
                                                       $urlEnd = '|/';
                                                       $this->file['Filename'] = str_replace(' ', '+', $this->file['Filename']);
                                                       $link = $urlStart.$this->file['Filename'].$uri.$urlEnd ;
                                                       }
                                elseif ( $val['Type'] == 1) {  $type = 'gnutella';
                                                        $urlStart = 'magnet:?xt=urn:ed2k:';
                                                       $uri = $val['Uri'];
                                                       $urlEnd = '|/';
                                                       $this->file['Filename'] = str_replace(' ', '+', $this->file['Filename']);
                                                       $link = $urlStart.$uri.$urlEnd ;
                                                       }
                                
                                elseif ( ( $val['Type'] == 3) || ( $val['Type'] == 7) ) { $type = 'bittorrent'  ;
                                                         }
                                 elseif ( ( $val['Type'] == 4) || ( $val['Type'] == 8) ){  $type = 'http'  ;


                                 }


                    ?>
                    
                    <?php
                    // don't paint tiger or md5 rows
                    if  (isset($type)) : ?>
                           

                        <div class="download_source" >
                                <a href="<?=$link ?>"><img alt="" src="/images/icons/<?=$type ?>_download.gif" />
                                <?='<b>'.ucfirst ( $type ).'</b><span>'.$val['Sources'].' '.$this->translate('sources');?></span></a>
                                <?='<input onClick="javascript:this.focus();this.select();" type="text"  value="'.$link.'" />'; ?>
                                <? unset ($type, $pinta, $link) ?>
                        </div>

                 <?php  endif; ?>




                <?php endforeach; ?>
            
        </div>
       <?php endif; ?>

   <? //Zend_Debug::dump($this->file);?>
   <? Zend_Debug::dump($this->metadata);?>
   <? //Zend_Debug::dump($this->sources);?>

        <div class="sharelinks"><?=$this->translate('Share this:');?>
            <a href="http://www.facebook.com/share.php?u=http://foof.in/<?=$this->lang;?>/<?=dechex($this->file['IdFile'] );?>">
                <img alt="share by facebook" src="/images/icons/ico_facebook.gif" border = "0"/></a>
                <a href="mailto:?subject=<?=$this->file['Filename'];?>&body=http://foofind.com./<?=$this->lang;?>/download/<?=$this->file['IdFile'];?>">
                <img alt="share by email" src="/images/icons/ico_email_link.png" border = "0"/></a>
                <a href="http://twitter.com/home?status=http://foof.in/<?=$this->lang;?>/<?=dechex($this->file['IdFile'] );?>">
                <img alt="share by twitter" src="/images/icons/ico_twitter.png" border = "0"/></a>
        </div>

    </div>


    <div class="download_more_info">
        <h3><?=$this->translate('How to download?'); ?></h3>
        <p><?=$this->translate('Para descargar el software enlazado en esta página se puede precisar un software externo.
            Aquí tienes algunos programas compatibles:'); ?></p>
        <p><img alt="eMule, MLDonkey, aMule"  src="/images/icons/ed2k.gif" /> eMule, MLDonkey, aMule</p>
        <p><img alt="Shareaza, Phex, Limewire"  src="/images/icons/gnutella.gif" /> Shareaza, Phex, Limewire</p>
        <p><img alt="µTorrent, Bittorrent, Transmission"  src="/images/icons/torrent.gif" /> µTorrent, BitTorrent,Transmission.</p>
    </div>


     </div>

</div>
