<?=$this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?=$this->headTitle()->setPrefix('foofind.com') ?>
  <?=$this->headLink()->appendStylesheet('/css/main.css') ?>
  <link rel="shortcut icon" href="/images/favicon.ico" />
</head>

<body>

<div id="header" ></div>

<div class="content">

    <div id="container_search">
    <h1>
        <a href="/" ><img border="0" src="/images/foofind_search.gif" alt="File search engine - Foodind" title="File search engine - foodind" /> </a>
    </h1>

    <hr />

     


    <?php echo $this->layout('error')->content ?>


</div>



 
<script type="text/javascript">if (window != top) top.location.href = location.href;</script>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-808946-19");
pageTracker._trackPageview();
} catch(err) {}</script>

</body>
</html>
