<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?=$this->headMeta();?>
        <?= $this->headTitle()->setPrefix('foofind.com');?>
        <?=$this->headLink()->appendStylesheet('/css/main.css');?>
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Foofind" />
        <?=$this->jQuery();?>
        <? include_once("header_common.phtml");?>
    </head>
    <body OnLoad="document.getElementById('q').focus();">

        <div id="header" >
            <div id="header-navigation" >
                <span class="select_language_box">

                    <?
                    $url = $_SERVER['REQUEST_URI'] ;
                    if ($url=='/') $url .= $this->lang.'/';
                    if ($this->lang == 'es')
                    {
                        $url = str_replace('/es/', '/en/', $url);
                        echo "<a href= '{$url}'>English</a>";
                    }
                    elseif ($this->lang == 'en')
                    {
                        $url = str_replace('/en/', '/es/', $url);
                        echo "<a href= '{$url}'>Español</a>";
                    }
?>
                </span>
            </div>
        </div>

        <div class="content">
<?=$this->layout()->content ?>

            <div id="footer_main" >
                <p><?=$this->translate('this is the footer text');  ?></p>
            </div>
        </div>


    </body>
</html>