<? echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?= $this->headTitle()->setPrefix('foofind.com') ?>




  <?php echo $this->jQuery(); ?>
  <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
</head>

<body>

<div id="header" >
    <div id="header-navigation" style="float: right">
        <a href="/page/about">About foofind</a>
    </div>
</div>

<div class="content">
    <?php echo $this->layout()->content ?>
    <div id="footer_main" >
        <p>FooFind is an open source media search engine that lets you find music, videos, software and more.<br />
            Content of this website is under Creative Commons <a rel="license content" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">BY-NC-SA</a> license.
            Source code under <a rel="license source code" href="http://www.gnu.org/licenses/gpl-3.0.txt">GPLv3</a> license.</p>
    </div>
</div>

</body>
</html>
