<? echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>FooFind.com</title>

  <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
</head>

<body>

<div id="header" >

    <div id="header-navigation" style="float: right">

        <a href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">About Foo Find</a>

    </div>

</div>

<div class="content">
    <?php echo $this->layout()->content ?>
</div>


<div id="footer" >

    <div id="footer-navigation" >
        <a href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Submit links</a>
        <a href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Terms</a>
        <a href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Privacy</a>
        <a href="http://code.google.com/p/foofind/">Developers</a>
    </div>

</div>


</body>
</html>
