<? echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>FooFind.com</title>

  <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
</head>

<body>

<div id="header" ></div>

<div class="content">



    <div id="container_search">


    <h1>
        <a href="/" ><img border="0" src="../images/foofind_search.gif" alt="File search engine - Foodind" title="File search engine - foodind" /> </a>
    </h1>

     <hr />

     <div id="menu_page">


     <ul >

            About
            <li><a  href="/page/about" >About</a></li>
            <li><a  href="/contact" >Contact</a></li>
            <br /><br />
            Legal
            <li><a  href="/page/tos" >Terms</a></li>
            <li><a  href="/page/privacy" >Privacy</a></li>
            <li><a  href="/page/licenses" >Licenses</a></li>
            <br /><br />
            Links
            <li><a  href="/page/submit" >Submit links</a></li>
            <li><a  href="/complaint" >Report links</a></li>
            <br /><br />
            Developers
            <li><a  href="http://code.google.com/p/foofind/" >Source code</a></li>
            <li><a  href="/page/api" >Api</a></li>
            
        </ul>



     </div>


    <?php echo $this->layout('page')->content ?>


</div>

<div id="footer_main" >

    <p>foofind is an open source media search engine that lets you find music, videos, software and more.<br />
        Content of this website is under Creative Commons <a rel="license content" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">BY-NC-SA</a> license.
        Source code under <a rel="license source code" href="http://www.gnu.org/licenses/gpl-3.0.txt">GPLv3</a> license.</p>
</div>

</div>

</body>
</html>
