<? include_once("header_common_nosearch.phtml");?>
<div id="container_search">
    <h1>
        <a href="/" ><img border="0" src="<?=STATIC_PATH;?>/images/foofind_search.gif" alt="File search engine - Foodind" title="File search engine - foodind" /> </a>
    </h1>
    <hr />
    <div id="menu_page">
        <ul >
            <li><a  href="/<?=$this->lang?>/page/about" ><?=$this->translate('About');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/contact" ><?=$this->translate('Contact');?></a></li>
            <br /><br />
            <li><a  href="/<?=$this->lang?>/page/legal" ><?=$this->translate('Legal');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/tos" ><?=$this->translate('Terms');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/privacy" ><?=$this->translate('Privacy');?></a></li>
            <br /><br />
            <li><a  href="/<?=$this->lang?>/page/complaint" ><?=$this->translate('Report links');?></a></li>
            <br /><br />
            <li><a  href="http://code.google.com/p/foofind/" ><?=$this->translate('Source code');?></a></li>
        </ul>
    </div>
    <?php echo $this->layout('page')->content ?>
</div>
<div id="footer_main" >
    <p><?=$this->translate('this is the footer text');  ?></p>
    <p><a href="/es/index/lastfiles" ><?=$this->translate('Last indexed files.'); ?></a></p>
</div>
</body>
</html>