<? include_once("header_common.phtml");?>

<div id="container_search">
    <h1>
        <a href="/" ><img  src="/images/foofind_search.gif" alt="File search engine - foofind.com" title="File search engine - foofind.com" /></a>
    </h1>

    <?
        require_once APPLICATION_PATH . '/forms/Search.php';
        $form = new Form_Search( );
        
        $form->setAction( '/'. $this->lang.'/search/');
        $form->loadDefaultDecoratorsIsDisabled(false);
        foreach($form->getElements() as $element) {
            $element->removeDecorator('DtDdWrapper');
            $element->removeDecorator('Label');
        }

        echo $form; ?>
    

    <hr />

    

         <?php echo $this->layout('with_search_form')->content ?>
       
       


    



<div id="footer_main" >
                <p><?=$this->translate('this is the footer text');  ?></p>
            </div>
        </div>


    </body>
</html>