<div id="container_search">
    <h1>
        <a href="/" ><img border="0" src="/images/foofind_search.gif" alt="File search engine - Foofind" title="File search engine - foofind" /> </a>
    </h1>

<?php if ($this->key) echo "<div style='clear:both;'><a href='/metadata'>Back</a></div>"; ?>
    <div style="clear:both; width:100%;">
<?php $i = 0;
      foreach ($this->paginator as $key => $val):
         if ($i>0 && $i%10==0) echo "</table>";
         if ($i%10==0) echo "<table border='0' style='margin:5px;table-layout: fixed; float:left; width:49%; background-color: #EEEEEE;'>"
                            ."<th style='text-align:center; width:27%; padding: 2px;background-color: #fff; margin:1px'>Key</th>"
                            ."<th style='text-align:center; width:18%; padding: 2px;background-color: #fff; margin:1px'>Count</th>"
                            ."<th style='text-align:center; width:45%; padding: 2px;background-color: #fff; margin:1px'>Value</th>"
                            ."<th style='text-align:center; width:10%; padding: 2px;background-color: #fff; margin:1px'>Encoded</th>";
         $i+=1;?>
    <tr>
        <td style="padding: 2px;background-color: #fff;  margin:1px"><a href="<?=$this->url(array('key'=>$val["CrcKey"], 'page'=>1)) ?>"><?=$val["KeyMD"]?></a></td>
        <td style="text-align:center; padding: 2px;background-color: #fff; margin:1px"><?=$val["Count"]?></td>
        <td style="overflow:hidden; padding: 2px;background-color: #fff; margin:1px"><?=$val["ValueMD"]?></td>
        <td style="overflow:hidden; padding: 2px;background-color: #fff; margin:1px"><?=$val["IdEncoded"]?></td>
    </tr>

<?php   
      endforeach; ?>
    </table>
    </div>
    <p style="clear:both;">&nbsp;</p>
    <?=$this->paginationControl($this->paginator,'Sliding','paginator_md.phtml'); ?>
</div><!-- end of container_search --->