<?php
/**
 * complaint  page
 */
$this->page_title = $this->translate ( 'Complaint form' ) . ' - foofind.com';?>



    
    <a href="/" class="logo"><img border="0" src="../images/foofind.gif" alt="File search engine - Foodind" title="File search engine - Foodind" /></a>
<div class="container_form">
<h2>Complaint form</h2>



<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">


		<?=$this->form?>


</form>


</div>


