<div id="container_user">
<h2><?=$this->translate('Forgot your password?')?></h2>
<p>
<?=$this->translate ( '(If you already are a registered user, please' );?>&nbsp;
<a href="/<?=$this->lang?>/auth/login" title="user login"><?=$this->translate ( 'login here' );?></a>)
</p>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>
<?php endif;?>

<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">
<p><?=$this->translate ( 'Please, enter your email address. An email to recover your access will be sent to you.' );?></p>
<?=$this->form;?>
</form>
<?=$this->translate ( 'The email address must be the same you used to register.' )?>
</div>
