<?php if ($this->pageCount): ?>
<div class="pagination">

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->qs(array('page'=>$this->previous)); ?>"><span id="prev"><?=$this->translate('Previous');?></span></a>
<?php else: ?>
 <span id="prev"><?=$this->translate('Previous'); ?></span>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page):?><?php if ($page != $this->current): ?><a href="<?php echo $this->qs(array('page'=>$page)) ?>"><span id="norm" ><?php echo $page; ?></span></a><?php else: ?><span id="current"><?php echo $page; ?></span><?php endif; ?><?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->qs(array('page'=>$this->next)) ?>"><span id="next"> <?=$this->translate('Next'); ?></span></a>
<?php else: ?>
<span id ="next" class="disabled"><?=$this->translate('Next'); ?></span>
<?php endif; ?>

</div>
<?php endif; ?>
