<?=$this->headTitle()->append($this->translate('Report links'));?>


<div id="container_page">
    
    <h2><?=$this->translate('Report links')?></h2>

    <? //Zend_Debug::dump($this->form) ?>
        <form action="<?=$this->escape ( $this->form->getAction () )?>"
                method="<?=$this->escape ( $this->form->getMethod () )?>">


<?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->error ;?>
    </div>
    <?php endif;?>

                        <?
            echo $this->form->name;
            echo $this->form->surname;
            echo $this->form->company;
            echo $this->form->email;
            echo $this->form->phonenumber;
            echo $this->form->linkreported;
            echo $this->form->urlreported;
            echo $this->form->reason;
            echo $this->form->message;

            echo $this->form->captcha; ?>

            <span id="agree">
            <?=$this->form->agree.$this->translate('literal_check_agree');?>
            </span>
            <? echo $this->form->submit; ?>

        </form>


</div>

