<?=$this->headTitle()->append($this->translate('Contact form'));?>
<h2><?=$this->translate('Contact form')?></h2>
<p class="warning"><?=$this->translate("Note: If you are claiming for a link removal, you must use <a href='/en/page/complaint'>report link form</a>. Complaints done trough this form will be ignored.")?></p>
<form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
<?php
if (isset ( $this->error )) :
    ?>
<div class="error">
        <?=$this->escape ( $this->error );?>
</div>
<?php endif;?>
<?

        echo $this->form->email;
        echo $this->form->message;
        echo $this->form->captcha; ?>
        <span id="agree">
        <?=$this->form->agree.$this->translate('literal_check_agree');?>
        </span>
        <? echo $this->form->submit; ?>
</form>