<?=$this->headTitle()->append($this->translate('Submit links'));?>
<h2><?=$this->translate('Submit links')?></h2>
<form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
<p><?=$this->translate("Please include one http, ftp, ed2k or magnet link per line.<br />It will be crawled automatically and added to search results shortly.");?></p>
<?php
if (isset ( $this->error )) :
    ?>
<div class="error">
        <?=$this->escape ( $this->error );?>
</div>
<?php endif;?>
<?
        echo $this->form->urls;
        echo $this->form->captcha; ?>
        <span id="agree">
        <?=$this->form->agree.$this->translate('literal_check_agree');?>
        </span>
        <? echo $this->form->submit; ?>
</form>