<center id="container_home">
    <div title="foofind" class="logo_home"><p><?=$this->totalFilesIndexed; ?> files indexed</p></div>

    <?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>




    <div class="home_form">
        <?echo $this->form;?>
    </div>

    <div id="footer_home" >

    <div id="footer-navigation" >
        <a class="navtype" href="/page/submit">Submit links</a>
        <a class="navtype" href="/page/tos">Terms</a>
        <a class="navtype" href="/page/privacy">Privacy</a>
        <a class="navtype" href="http://code.google.com/p/foofind/">Developers</a>
    </div>

</div>
</center>