<center id="container_home">
    <div title="foofind" class="logo_home"><p><?=$this->totalFilesIndexed.' '.$this->translate('files indexed');?></p></div>

    <div class="home_form">
        <?=$this->form;?>
    </div>

    <div id="footer_home">
        <div id="footer-navigation" >
            <a class="navtype" href="/<?=$this->lang?>/page/legal/"><?=$this->translate('Legal');?></a>
            <a class="navtype" href="/<?=$this->lang?>/page/tos"><?=$this->translate('Terms');?></a>
            <a class="navtype" href="/<?=$this->lang?>/page/privacy"><?=$this->translate('Privacy');?></a>
        </div>
    </div>
</center>