<div id="container_home">
    <div title="foofind" class="logo"><p>I. Want. That. File.</p></div>
    <?
    if (count($this->mensajes) > 0) {
        echo '<div class="success">';
        foreach ($this->mensajes as $msg) {
            echo $msg . '<br>';
        }
        echo '</div>';
    }
    ?>
    <div class="search">
        <div class="tabs">
            <a class="<?=(preg_match("/^$/",  $this->qs['type']))?"actual":""?>" t="" href="/" ><?=$this->translate('All');?></a>
            <a class="<?=(preg_match("/^Audio$/", $this->qs['type']))?"actual":""?>" t="Audio" href="/?type=Audio" ><?=$this->translate('Audio');?></a>
            <a class="<?=(preg_match("/^Video$/", $this->qs['type']))?"actual":""?>" t="Video" href="/?type=Video" ><?=$this->translate('Video');?></a>
            <a class="<?=(preg_match("/^Image$/", $this->qs['type']))?"actual":""?>" t="Image" href="/?type=Image" ><?=$this->translate('Image');?></a>
            <a class="<?=(preg_match("/^Document$/", $this->qs['type']))?"actual":""?>" t="Document" href="/?type=Document" ><?=$this->translate('Document');?></a>
            <a class="<?=(preg_match("/^Software$/", $this->qs['type']))?"actual":""?>" t="Software" href="/?type=Software" ><?=$this->translate('Software');?></a>
            <a class="<?=(preg_match("/^Archive$/", $this->qs['type']))?"actual":""?>" t="Archive" href="/?type=Archive" ><?=$this->translate('Archive');?></a>
        </div>
        <div class="form">
            <?= $this->form; ?>
            <script>document.getElementById('q').focus();</script>
        </div>
    </div>

    <div class="social_widgets">
        <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Ffoofind.com&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no"
                frameborder="0" style="border:none; overflow:hidden; width:380px; padding-right: 20px; height:50px;" allowTransparency="true"></iframe>
        <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://foofind.com" data-text="Foofind" data-count="horizontal" data-via="foofind">Tweet</a>
        <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    </div>
</div>
