<div id="container_user">
    <h2><?=$this->translate('Last indexed files') .' '. date( $this->translate('l dS \o\f F Y H:i:s') ) . ' (GMT+01:00) , Madrid' ?></h2>
<div id="results">
    <ul>
       <?php foreach ($this->lastfiles as $key => $file):
                    foreach ($file['src'][0]['fn'] as $key => $value)
                            { //   bazinga!
                            } 
           ?>
        <li class="file_excerpt">
            <h3><a href="/<?=$this->lang?>/download/<?=$file['src'][0]['uri'] ?>/<?=$value['n'].'.html'; ?>"><?=$value['n']; ?></a></h3>
        </li>
        <?php          
            endforeach; ?>
    </ul>
    </div>
<?=$this->paginationControl($this->lastfiles,'Sliding','paginator_md.phtml'); ?>
<br />

    <div class="alfa">
        <?
        $LETRAS = range( 'a', 'z' );
        foreach( $LETRAS as $LETRA ) {
             $letras = range( 'a', 'z' );
             foreach( $letras as $letra ) {
                echo '<a href="/'.$this->lang.'/search/?q='.$LETRA.$letra.'*">'.$LETRA.$letra.'</a>&nbsp;<wbr>';
             }
        }
      
        $NUMEROS = range( '0', '9' );
        foreach( $NUMEROS as $NUMERO ) {
             $numeros = range( '0', '9' );   
                  foreach( $numeros as $numero ) {
                        if ( $NUMERO.$numero != '00'){
                            echo '<a href="/'.$this->lang.'/search/?q='.$NUMERO.$numero.'*">'.$NUMERO.$numero.'</a>&nbsp;<wbr>';
                         }
             }      
        }
        ?>
    </div>
</div>