<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=7" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?=$this->headTitle()->setPrefix('foofind.com');?>
        <?=$this->headLink()->appendStylesheet( STATIC_PATH . '/css/main.css');?>
        <link rel="shortcut icon" href="<?=STATIC_PATH ;?>/images/favicon.ico" />
        <? include_once("header_common_nosearch.phtml");?></head>
    <body>
        <div id="header" ></div>
        <div class="content<?php if ($this->advices) { echo " advices";}?>">
            <div id="container_error">
                <h1>
                    <a href="/" class="logo_site"><div></div><span>File search engine - foofind.com</span></a>
                </h1>
                <hr />
                <?php echo $this->layout('error')->content ?>
            </div>
          </div>
    </body>
</html>
