<? include_once("header_common.phtml");?>
<div class="content<?php if ($this->advices) { echo " advices";}?>">
<div id="container_search">
    <h1>
        <a href="/" class="logo_site"><div></div><span>File search engine - <?=WEB_PATH?></span></a>
    </h1>
    <?
    require_once APPLICATION_PATH . '/forms/Search.php';
    $form = new Form_Search( );

    $form->setAction( '/'. $this->lang.'/search/');
    $form->loadDefaultDecoratorsIsDisabled(false);
    foreach($form->getElements() as $element)
    {
        $element->removeDecorator('DtDdWrapper');
        $element->removeDecorator('Label');
    }
echo $form; ?>
    <hr />
    <script>document.getElementById('q').focus();</script>
    <?php echo $this->layout('with_search_form')->content ?>
    <div id="footer">
        <span id="footer_text"><?=$this->translate('this is the footer text');  ?></span>
        <span id="footer_links">
            <a class="navtype" href="/<?= $this->lang ?>/page/about/"><?= $this->translate('About'); ?></a>
            <a class="navtype" href="/<?= $this->lang ?>/page/legal/"><?= $this->translate('Legal'); ?></a>
            <? if ($this->lang=="es"): ?><a class="navtype" href="/<?= $this->lang ?>/page/jobs/">Trabaja con nosotros</a><? endif; ?>
            <a class="navtype" href="/<?= $this->lang ?>/index/lastfiles" ><?= Zend_Locale_Format::toNumber(  Zend_Registry::get("files_count"), array( 'locale' => $this->lang))?> <?=$this->translate('files indexed'); ?></a>
        </span>
    </div>
</div>
</div>
</body>
</html>