<div id="container_user">
<? if (strlen($this->message)>0): ?>
    <h2><?=$this->translate($this->message)?></h2>
<? else: ?>
    <h2><?=$this->translate('User login')?></h2>
<? endif; ?>
<p>
<?=$this->translate ( '(If you are a new user, please' );?>
&nbsp;<a href="/<?=$this->lang?>/user/register" title="user register"><?=$this->translate ( 'register here' );?></a>)
</p>

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>

<?php endif;?>


<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<?=$this->form;?>
<br />
<a href="/<?=$this->lang ?>/user/forgot">
<?=$this->translate ( 'Forgot' );?></a> <?=$this->translate ( 'your password?' );?>

</form>
</div><!-- end of container_page --->
