<?php


function formatLength($text)
{
    $secs = (int)$text;
    $mins = 0;
    if ($secs>59) {
        $mins = $secs/60;
        $secs = $secs%60;
        if ($mins>59) {
            $hours = $mins/60;
            $mins = $mins%60;
        }
    }
    if ($hours)
        return sprintf("%d:%02d:%02d", $hours, $mins, $secs);
    else
        return sprintf("%d:%02d", $mins, $secs);
}

function format($context, $md, $show_title)
{
    return "";
}

function formatAudio($context, $md, $show_title)
{
    $res = '';
    if ($artist = $md["audio:artist"]) $res .= $context->translate("Artist:")."&nbsp;$artist. ";
    if ($title = $md["audio:title"]) $res .= $context->translate("Title:")."&nbsp;$title. ";
    if ($album = $md["audio:album"]) {
        $res .= $context->translate("Album:")."&nbsp;$album";
        if (($year = $md["audio:year"]) && is_numeric($year) && $year>1901 && $year<2100)
            $res .= "&nbsp;($year). ";
        else
            $res .= ". ";
    }
    if ($genre = $md["audio:genre"]) $res .= $context->translate("Genre:")."&nbsp;$genre. ";
    if ($len = $md["audio:seconds"]) $res .= $context->translate("Length:")."&nbsp;".formatLength($len).". ";
    if ($bitrate = $md["audio:bitrate"]) $res .= $context->translate("Bitrate:")."&nbsp;$bitrate&nbsp;kbit/s. ";
    return $res;
}

function formatDocument($context, $md, $show_title)
{
    $res = '';
    if ($show_title && $title = $md["document:title"]) $res .= "$title<br/>";
    if ($pages = $md["document:pages"]) $res .= $context->translate("Nº of pages:")."&nbsp;$pages. ";
    return $res;
}

function formatImage($context, $md, $show_title)
{
    $res = '';
    if ($show_title && $title = $md["image:title"]) $res .= "$title<br/>";
    if (($width = $md["image:width"]) && ($height = $md["image:height"]))
        $res .= $context->translate("Size:")."&nbsp;${width}x$height. ";
    if ($colors = $md["image:colors"]) $res .= $context->translate("Colors:")."&nbsp;$colors. ";
    return $res;
}

function formatVideo($context, $md, $show_title)
{
    $res = '';
    if ($show_title && $title = $md["video:title"]) $res .= "$title<br/>";
    if (($len = $md["video:minutes"]*60) || ($len = $md["video:length"]))
        $res .= $context->translate("Length:")."&nbsp;".formatLength($len).". ";
    if (($width = $md["video:width"]) && ($height = $md["video:height"]))
        $res .= $context->translate("Size:")."&nbsp;${width}x$height. ";
    return $res;
}

function formatSoftware($context, $md, $show_title)
{
    $res = '';
    if ($show_title && $title = $md["application:title"]) $res .= "$title<br/>";
    return $res;
}

function formatArchive($context, $md, $show_title)
{
    $res = '';
    if ($files = $md["archive:files"])
        $res .= $context->translate("Files:")."&nbsp;$files. ";
    return $res;
}
?>

<div id="container_search">
    <h1>
        <a href="/" ><img border="0" src="/images/foofind_search.gif" alt="File search engine - foofind.com" title="File search engine - foofind.com" /></a>
    </h1>

<?=$this->form; ?>


    <div class="contentype">
        <a class="<?=(preg_match("/^$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array(), array('type'=>1, 'page'=>1)) ?>" ><?=$this->translate('All');?></a>
        <a class="<?=(preg_match("/^Audio$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Audio'), array('page'=>1)) ?>" ><?=$this->translate('Audio');?></a>
        <a class="<?=(preg_match("/^Video$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Video'), array('page'=>1)) ?>" ><?=$this->translate('Video');?></a>
        <a class="<?=(preg_match("/^Image$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Image'), array('page'=>1)) ?>" ><?=$this->translate('Image');?></a>
        <a class="<?=(preg_match("/^Document$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Document'), array('page'=>1)) ?>" ><?=$this->translate('Document');?></a>
        <a class="<?=(preg_match("/^Software$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Software'), array('page'=>1)) ?>" ><?=$this->translate('Software');?></a>
        <a class="<?=(preg_match("/^Archive$/", $_GET['type']))?"actual":""?>" href="<?= $this->qs(array('type'=>'Archive'), array('page'=>1)) ?>" ><?=$this->translate('Archive');?></a>
    </div>
 
    <div class="search_info">Results <?=$this->info['start']?> - <?=$this->info['end']?> of about <?=number_format($this->info['total'], 0) ?> for <?=$this->info['q']?> (<?=$this->info['time']?> seconds)<span class="debuginfo"><?=$this->info['time_desc']?></span></div>
    <hr />



    <div id="options">
   <div class="cornerBox">
    <div class="corner TL"></div>
    <div class="corner TR"></div>
    <div class="corner BL"></div>
    <div class="corner BR"></div>
    <div class="cornerBoxInner">
        <p><?=$this->translate('Include results from:')?></p>
            <ul class="sourcetype">
                <li><a class="<?=(strpos($this->src['ed2k'], 'e')===false)?"on":"off" ?>" href="<?= $this->qs(array('src'=>$this->src['ed2k']), array('page'=>1)) ?>" ><img src='/images/icons/ed2ki.gif' style='vertical-align:middle;border:none'><?=$this->translate('Ed2k');?></a></li>
                <li><a href="<?= $this->qs(array('src'=>$this->src['magnet']), array('page'=>1)) ?>" class="<?=(strpos($this->src['magnet'], 'm')===false)?"on":"off"?>" ><img src='/images/icons/magneti.gif' style='vertical-align:middle;border:none'><?=$this->translate('Magnet');?></a></li>
                <li><a href="<?= $this->qs(array('src'=>$this->src['torrent']), array('page'=>1)) ?>" class="<?=(strpos($this->src['torrent'], 't')===false)?" on":"off"?>" ><img src='/images/icons/torrenti.gif' style='vertical-align:middle;border:none'><?=$this->translate('BitTorrent');?></a></li>
                <li><a href="<?= $this->qs(array('src'=>$this->src['web']), array('page'=>1)) ?>" class="<?=(strpos($this->src['web'], 'w')===false)?" on":"off"?>" ><img src='/images/icons/webi.gif' style='vertical-align:middle;border:none'><?=$this->translate('Web');?></a></li>
                <li><a href="<?= $this->qs(array('src'=>$this->src['ftp']), array('page'=>1)) ?>" class="<?=(strpos($this->src['ftp'], 'f')===false)?" on":"off"?>" ><img src='/images/icons/ftpi.gif' style='vertical-align:middle;border:none'><?=$this->translate('Ftp');?></a></li>
            </ul>
    </div>
    </div>
    <div id="advsearch">
    <div id="common">
        <ul class="size">
            <li><a class="<?=(preg_match("/^$/", $_GET['size']))?"actual":""?>" href="<?= $this->qs(array('opt'=>1), array('size'=>1, 'page'=>1)) ?>" ><?=$this->translate('All sizes');?></a></li>
            <li><a class="<?=(preg_match("/^1$/", $_GET['size']))?"actual":""?>" href="<?= $this->qs(array('size'=>'1', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Smaller than');?> 1MB</a></li>
            <li><a class="<?=(preg_match("/^2$/", $_GET['size']))?"actual":""?>" href="<?= $this->qs(array('size'=>'2', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Smaller than');?> 10MB</a></li>
            <li><a class="<?=(preg_match("/^3$/", $_GET['size']))?"actual":""?>" href="<?= $this->qs(array('size'=>'3', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Smaller than');?> 100MB</a></li>
            <li><a class="<?=(preg_match("/^4$/", $_GET['size']))?"actual":""?>" href="<?= $this->qs(array('size'=>'4', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Larger than');?> 100MB</a></li>
        </ul>
    </div>
        <?php if (preg_match("/^Audio$/", $_GET['type'])): ?>
        <ul class="quality">
            <li><a class="<?=(preg_match("/^$/", $_GET['brate']))?"actual":""?>" href="<?= $this->qs(array('opt'=>1), array('brate'=>1, 'page'=>1)) ?>" ><?=$this->translate('All qualities');?></a></li>
            <li><a class="<?=(preg_match("/^1$/", $_GET['brate']))?"actual":""?>" href="<?= $this->qs(array('brate'=>'1', 'opt'=>1), array('page'=>1)) ?>" >128 kbps <?=$this->translate('or better');?></a></li>
            <li><a class="<?=(preg_match("/^2$/", $_GET['brate']))?"actual":""?>" href="<?= $this->qs(array('brate'=>'2', 'opt'=>1), array('page'=>1)) ?>" >192 kbps <?=$this->translate('or better');?></a></li>
            <li><a class="<?=(preg_match("/^3$/", $_GET['brate']))?"actual":""?>" href="<?= $this->qs(array('brate'=>'3', 'opt'=>1), array('page'=>1)) ?>" >256 kbps <?=$this->translate('or better');?></a></li>
            <li><a class="<?=(preg_match("/^4$/", $_GET['brate']))?"actual":""?>" href="<?= $this->qs(array('brate'=>'4', 'opt'=>1), array('page'=>1)) ?>" >320 kbps <?=$this->translate('or better');?></a></li>
        </ul>
        <?php endif; ?>
        <?php if (preg_match("/^Audio|Video$/", $_GET['type'])): ?>
        <ul class="year">
            <li><a class="<?=(preg_match("/^$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('opt'=>1), array('year'=>1, 'page'=>1)) ?>" ><?=$this->translate('All years');?></a></li>
            <li><a class="<?=(preg_match("/^1$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'1', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Before');?> 1960</a></li>
            <li><a class="<?=(preg_match("/^2$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'2', 'opt'=>1), array('page'=>1)) ?>" >60's</a></li>
            <li><a class="<?=(preg_match("/^3$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'3', 'opt'=>1), array('page'=>1)) ?>" >70's</a></li>
            <li><a class="<?=(preg_match("/^4$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'4', 'opt'=>1), array('page'=>1)) ?>" >80's</a></li>
            <li><a class="<?=(preg_match("/^5$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'5', 'opt'=>1), array('page'=>1)) ?>" >90's</a></li>
            <li><a class="<?=(preg_match("/^6$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'6', 'opt'=>1), array('page'=>1)) ?>" >00's</a></li>
            <li><a class="<?=(preg_match("/^7$/", $_GET['year']))?"actual":""?>" href="<?= $this->qs(array('year'=>'7', 'opt'=>1), array('page'=>1)) ?>" ><?=$this->translate('Last year');?></a></li>
        </ul>
        <?php endif; ?>
    </div>
    </div>

<?php if ($this->info['total']>0): ?>
    <div id="results">
    <ul>
       <?php foreach ($this->paginator as $key => $val): ?>
        <li class="file_excerpt">
            <h3><a href="<?=$val['rlink'] ?>"><?=$val['filename'] ?></a><span class="debuginfo">id: <?=$key ?> w:<?=$val['weight'] ?> fw:<?=$val['fileweight'] ?> fnc:<?=$val['attrs']['fncount'] ?> s:<?=$val['isources'] ?></span></h3>
            <span>
              <?php
                if ($val['type']!=null) {
                    $func = 'format'.$val['type'];
                    echo $func($this, $val['md'], !$val['in_filename']);
                }
              ?></span>
            <?php if ($val["sources"]): ?><span><?=$this->translate('Sources');?>:
                <?php foreach ($val["sources"] as $k => $v): ?>
                    <?= "<img title='${v['tip']}' alt='${v['tip']}' src='/images/icons/${k}d.gif' style='vertical-align:middle'>${v['count']} " ?>
                <?php endforeach; ?></span>
            <?php endif; ?>
            <cite><?=$val['link']?></cite>
            <? if ($val['size']) echo " - ".$val["size"]?>
        </li>
        <?php endforeach; ?>
    </ul>
    </div>

    <?=$this->paginationControl($this->paginator,'Sliding','paginator_search.phtml'); ?>
    
<?php else: ?>
    <h2><?=$this->translate('No results.');?></h2>
<?php endif;?>

</div><!-- end of container_search --->
