
  
  <h2><?php echo $this->message ?></h2>


 <?php if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

  <center>
  <object width="320" height="245"><param name="movie" value="http://www.dailymotion.com/swf/x2c9er&colors=special:EBE8E1;&autoPlay=1"></param><param name="allowFullScreen" value="true"></param><param name="allowScriptAccess" value="always"></param>
      <embed src="http://www.dailymotion.com/swf/x2c9er&colors=special:EBE8E1;&autoPlay=1" width="320" height="245" allowfullscreen="true" allowscriptaccess="always"></embed></object>
</center>
   
