<?php if ($this->pageCount > 1): ?>
<div class="cpagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo "?page={$this->previous}"; ?>">«</a>&nbsp;
<?php else: ?>«&nbsp;<?php endif; ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo"?page={$page}" ?>"><span id="norm"><?php echo $page; ?></span></a>
  <?php else: ?>
    <span id="current"><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>&nbsp;<a href="<?php echo "?page={$this->next}"; ?>">»</a>
<?php else: ?>&nbsp;»<?php endif; ?>
</div>
<?php endif; ?>