<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?=$this->headTitle()->setPrefix('foofind.com');?>
        <?=$this->headLink()->appendStylesheet( STATIC_PATH . '/css/main.css');?>
        <link rel="shortcut icon" href="<?=STATIC_PATH ;?>/images/favicon.ico" />
        <? include_once("header_common.phtml");?></head>
    <body>
        <div id="header" ></div>
        <div class="content">
            <div id="container_search">
                <h1>
                    <a href="/" ><img border="0" src="<?=STATIC_PATH ;?>/images/foofind_search.gif" alt="File search engine - Foodind" title="File search engine - foodind" /> </a>
                </h1>
                <hr />
                <?php echo $this->layout('error')->content ?>
            </div>
          </div>
    </body>
</html>
