<center id="container_home">
    <div title="foofind" class="logo_home"><p><?=$this->totalFilesIndexed; ?> files indexed</p></div>
    <div class="home_form">
        <?echo $this->form;?>
    </div>

    <div id="footer_home" >

    <div id="footer-navigation" >
        <a class="navtype" href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Submit links</a>
        <a class="navtype" href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Terms</a>
        <a class="navtype" href="<?php echo $this->url(array('controller'=>'page'),'default',true) ?>">Privacy</a>
        <a class="navtype" href="http://code.google.com/p/foofind/">Developers</a>
    </div>

</div>
</center>