<div id="container_home">
    <div class="valign_home" style="height:35%; min-height: 150px;">
        <div><div title="foofind" class="logo"></div><div id="legend" <?=in_array($this->lang, array("zh", "pt"))?" class='small'":""?>><?=$this->translate('I. Want. That. File.')?></div></div>
    </div>

    <div class="valign_home" style="height:42%;">
    <div class="search">
    <?
    if (count($this->mensajes) > 0) {
        echo '<div class="success">';
        $sep="";
        foreach ($this->mensajes as $msg) {
            echo $msg.$sep;
            $sep='<br/>';
        }
        echo '</div>';
    }
    ?>
        <div class="form" nowrap>
        <div class="tabs" nowrap>
            <a class="ss <?=(preg_match("/^$/",  $this->qs['type']))?"actual":""?>" href="/" ><?=$this->translate('All');?></a>
            <a class="ss <?=(preg_match("/^Audio$/", $this->qs['type']))?"actual":""?>" href="/?type=Audio" ><?=$this->translate('Audio');?></a>
            <a class="ss <?=(preg_match("/^Video$/", $this->qs['type']))?"actual":""?>" href="/?type=Video" ><?=$this->translate('Video');?></a>
            <a class="ss <?=(preg_match("/^Image$/", $this->qs['type']))?"actual":""?>" href="/?type=Image" ><?=$this->translate('Image');?></a>
            <a class="ss <?=(preg_match("/^Document$/", $this->qs['type']))?"actual":""?>" href="/?type=Document" ><?=$this->translate('Document');?></a>
            <a class="ss <?=(preg_match("/^Software$/", $this->qs['type']))?"actual":""?>" href="/?type=Software" ><?=$this->translate('Software');?></a>
            <a class="ss <?=(preg_match("/^Archive$/", $this->qs['type']))?"actual":""?>" href="/?type=Archive" ><?=$this->translate('Archive');?></a>
        </div>
            <?= $this->form; ?>
            <script type="text/javascript">
                var tamingtime = 0;
                var textsearch = $("#q");
                textsearch.after("<div id='tamingresults'></div>");
                var tamingresults = $("#tamingresults");
                var lastsearch = "";

                function taming() {
                    lastsearch = textsearch.val();
                    if (lastsearch.length<2) {
                        lastsearch = "";
                        hideAutocomplete();
                        return;
                    }
                    type = $("#type").val();
                    if (type.length>0) type = "&t="+type;
                    $.ajax({
                        url:"/<?=$this->lang?>/taming/autocomplete?q="+escape(lastsearch)+type,
                        dataType:"json",
                        context: lastsearch,
                        error: function() {
                            tamingresults.html("");
                            hideAutocomplete();
                        },
                        success: function(d) {
                            if (this.context!=lastsearch) return;
                            if (lastsearch.length<2 || d==null || !d) {
                                tamingresults.html("");
                                hideAutocomplete();
                                return;
                            }
                            res = "";
                            t = lastsearch;
                            data = d;
                            for (l in data)
                            {
                                if (data[l][0]<0) break;
                                var i=0;
                                for (; i<t.length; i++)
                                    if (i>t.length || data[l][1][i]!=t[i]) break;
                                res += "<li>"+data[l][1].substr(0,i)+"<b>"+data[l][1].substr(i)+"</b></li>";
                            }
                            if (res.length>0) {
                                tamingresults.html("<ul>"+res+"</ul>");
                                $("li", tamingresults).click(selectAutocomplete);
                                $("li, b", tamingresults).mousemove(function(e){
                                    $("li.active", tamingresults).removeClass("active");
                                    if (e.target.localName=="li")
                                        it = e.target;
                                    else
                                        it = e.target.parentNode;
                                    activate($(it), false);
                                });
                                tamingresults.css("display","block");
                            } else {
                                tamingresults.html("");
                                hideAutocomplete();
                            }
                        }
                    })
                }
                function selectAutocomplete(e){
                    if (e.target.localName=="li")
                        it = e.target;
                    else
                        it = e.target.parentNode;
                    textsearch.val($(it).text());
                    hideAutocomplete();
                    $("form").submit();
                }
                function hideAutocomplete(){
                    if (tamingtime!=0) clearTimeout(tamingtime);
                    tamingresults.css("display","none");
                }
                function showAutocomplete(){
                    if (lastsearch=="" || lastsearch!=textsearch.val()) {
                        lastsearch = "";
                        tamingresults.html("");
                    }
                    if (tamingresults.html().length==0)
                        tamingresults.css("display","none");
                    else
                        tamingresults.css("display","block");
                }
                function delay(f, time){
                    return function() {
                        if (tamingtime!=0) clearTimeout(tamingtime);
                        tamingtime = setTimeout(f, time);
                    }
                }
                function activate(item, show)
                {
                    if (show) textsearch.val(item.text());
                    item.addClass("active");
                }
                textsearch.keydown(function(e) {
                    switch(e.which){
                        case 38:
                            e.preventDefault();
                            active = $("li.active", tamingresults);
                            last = $("li:last", tamingresults);

                            if (active.length==0)
                                activate(last, true);
                            else {
                                active.removeClass("active");
                                if (active.prev().length>0)
                                    activate(active.prev(), true);
                                else
                                    activate(last, true);
                            }
                            break;
                        case 40:
                            active = $("li.active", tamingresults);
                            first = $("li:first", tamingresults);
                            e.preventDefault();

                            if (active.length==0)
                                activate(first, true);
                            else {
                                active.removeClass("active");
                                if (active.next().length>0)
                                    activate(active.next(), true);
                                else
                                    activate(first, true);
                            }
                            break;
                        default:
                            delay(taming, 100)();
                            break;
                    }
                });
                textsearch.blur(delay(hideAutocomplete, 200));
                textsearch.focus(delay(showAutocomplete, 200));
            </script>
        </div>
    </div>
    </div>
    <div class="valign_home" style="height:23%; min-height: 90px;">
    <div class="social_widgets">
        <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Ffoofind.com&amp;layout=standard&amp;show_faces=false&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no"
                frameborder="0" style="border:none; overflow:hidden; width:380px; padding-right: 20px; height:50px;" allowTransparency="true"></iframe>
        <a href="http://twitter.com/share" class="twitter-share-button" data-url="http://foofind.com" data-text="Foofind" data-count="horizontal" data-via="foofind">Tweet</a>
        <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    </div>
    </div>
</div>
