<? header("Content-Type: text/xml;charset=iso-8859-1");
$datenow = date("Y-m-d", time() );
echo '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'; ?>

       <?php foreach ($this->lastfiles as $key => $val):
            if ($val['Filename']):?>

<?='<url>';?>

<loc><?='<![CDATA[http://foofind.com/'.$this->lang?>/download/<?=$val['IdFile'] ?>/<?=$val['Filename'].'.html]]>' ?></loc>
    
        <?php
        echo '
<lastmod>'.$datenow.'</lastmod>
   <changefreq>always</changefreq>
   <priority>0.7</priority>
</url>';
        endif;
            endforeach; ?>
<?='</urlset>';?>