<?=$this->headTitle()->append($this->translate('New user'));?>

<div id="container_page">

<h2><?=$this->translate('New user')?></h2>

<?=$this->translate ( '(If you already are a registered user, please' );?>&nbsp;
<a href="/<?=$this->lang?>/auth/login" title="user login"><?=$this->translate ( 'login here' );?></a>)

<?php
if (isset ( $this->error )) :
	?>
<div class="error">
		<?=$this->escape ( $this->error );?>
	</div>

<?php endif;?>


<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<legend><?=$this->translate ( 'Please, enter your email address. A new password will be emailed to you' );?></legend>

<?=$this->form;?>
</form>

<?=$this->translate ( 'The email address must be the same you used to register.' )?>

</div><!-- end of container_page --->
