<?=$this->doctype();?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?=$this->headMeta();?>
        <?= $this->headTitle()->setPrefix('foofind.com');?>
        <?=$this->headLink()->appendStylesheet('/css/main.css');?>
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="Foofind" />
        <?=$this->jQuery();?>


        <script type="text/javascript">if (window != top) top.location.href = location.href;</script>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-808946-19']);
            _gaq.push(['_trackPageview']);

            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();

        </script>


    </head>
    <body OnLoad="document.getElementById('q').focus();">

        <div id="header" >
            <div id="header-navigation" >

                <span class="user_login_box">
                    <?php

                    $auth = Zend_Auth::getInstance ();

                    if (! $auth->hasIdentity ())
                    {

                        echo '<a href="/' .  $this->lang . '/user/register">' . $this->translate ( 'new user' ) . '</a> ' .
                                $this->translate ( 'or' ) . ' ';
                        echo '<a href="/'  . $this->lang . '/auth/login">' . $this->translate ( 'login' ) . '</a>';
                    } else
                    {
                        $auth_username = $auth->getIdentity()->username;
                        $auth_userid = $auth->getIdentity()->id;


                        echo $this->translate ( 'hello,' ) . '<b>&nbsp;<a href="/' .
                                $this->lang . '/user/profile/id/' . $this->escape ( $auth_userid ) . '">' . $this->escape ( $auth_username ) . '</a></b> | ' . '<a href="/' . $this->lang . '/auth/logout">' .
                                $this->translate ( 'logout' ) . '</a>';
                    }

?>

                </span>&nbsp;&nbsp;

                <span class="select_language_box">

                    <?
                    $url = $_SERVER['REQUEST_URI'] ;
                    if ($url=='/') $url .= $this->lang.'/';
                    if ($this->lang == 'es')
                    {
                        $url = str_replace('/es/', '/en/', $url);
                        echo "<a href= '{$url}'>English</a>";
                    }
                    elseif ($this->lang == 'en')
                    {
                        $url = str_replace('/en/', '/es/', $url);
                        echo "<a href= '{$url}'>Español</a>";
}
?>
                </span>


            </div>
        </div>








