<? echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?= $this->headTitle()->setPrefix('foofind.com') ?>


  <?php echo $this->jQuery(); ?>
  <?php echo $this->headLink()->appendStylesheet('/css/main.css') ?>
</head>

<body OnLoad="document.getElementById('q').focus();">

<div id="header" >
    <div id="header-navigation" style="float: right">
        
    


<span class="select_language_box">
<select	name="site_language_code_select" id="site_language_code_select">
	<option <?=$this->lang == 'en' ? 'selected="selected"' : '';?>
		value="<?=$this->baseUrl . 'en'?>" id="en">English</option>
	<option <?=$this->lang == 'es' ? 'selected="selected"' : '';?>
		value="<?=$this->baseUrl . 'es'?>" id="es">Español</option>
</select>
</span>

</div>
</div>

<div class="content">
    <?php echo $this->layout()->content ?>
    <div id="footer_main" >
        <p>FooFind is an open source media search engine that lets you find music, videos, software and more.<br />
            Content of this website is under Creative Commons <a rel="license content" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">BY-NC-SA</a> license.
            Source code under <a rel="license source code" href="http://www.gnu.org/licenses/gpl-3.0.txt">GPLv3</a> license.</p>
    </div>
</div>




<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-808946-19");
pageTracker._trackPageview();
} catch(err) {}</script>
</body>
</html>
