<? include_once("header_common.phtml");?>

        <div class="content">
                <?=$this->layout()->content ?>

            <div id="footer_main" >
                <p><?=$this->translate('this is the footer text');  ?></p>
                <p><a href="/es/index/lastfiles" ><?=$this->translate('Last indexed files in realtime'); ?></a></p>
            </div>
        </div>


    </body>
</html>