<? include_once("header_common_nosearch.phtml");?>
<div class="content<?php if ($this->advices) { echo " advices";}?>">
        <?if ($this->advices):
            foreach ($this->advices as $name=>$advice):?>
            <div id="advice_<?=$name?>" class="advice"><?=$advice?> <a class="close_advice" href="#">&times;</a></div>
        <?  endforeach;
        endif;?>
    <div id="container_page">
    <h1>
        <a href="/" class="logo_site"><div></div><span>File search engine - foofind.com</span></a>
    </h1>
    <hr />
    <div id="menu_page">
        <ul >
            <li><a  href="/<?=$this->lang?>/page/about" ><?=$this->translate('About');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/contact" ><?=$this->translate('Contact');?></a></li>
            <? if ($this->lang=="es"): ?><li><a  href="/<?=$this->lang?>/page/jobs" >Ofertas de empleo</a></li><? endif;?>
            <br /><br />
            <li><a  href="/<?=$this->lang?>/page/legal" ><?=$this->translate('Legal');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/tos" ><?=$this->translate('Terms');?></a></li>
            <li><a  href="/<?=$this->lang?>/page/privacy" ><?=$this->translate('Privacy');?></a></li>
            <br /><br />
            <li><a  href="/<?=$this->lang?>/page/complaint" ><?=$this->translate('Report link');?></a></li>
            <br /><br />
            <li><a  href="/<?=$this->lang?>/page/translate" ><?=$this->translate('Translate');?></a></li>
            <li><a  href="http://code.google.com/p/foofind/" ><?=$this->translate('Source code');?></a></li>
        </ul>
    </div>
    <?php echo $this->layout('page')->content ?>
    </div>
<div id="footer" >
    <span id="footer_text"><?=$this->translate('this is the footer text');  ?></span>
</div>
</div>
</body>
</html>