<div id="container_page">

    <h2>Licenses</h2>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus elit tellus, malesuada vitae faucibus ut, commodo molestie turpis. Ut luctus mauris eu tortor gravida eu tempor lorem porta. Sed accumsan lacus nibh. Nulla fringilla dignissim orci, eget viverra justo ornare et. Fusce at sapien quis mauris porta faucibus non in tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis luctus lobortis vulputate. Vestibulum nec nisi non turpis suscipit imperdiet. Ut in lectus at purus sollicitudin interdum. Fusce ligula odio, placerat a dapibus vitae, venenatis in turpis. Etiam quam dolor, interdum vitae pretium vitae, hendrerit a est. Fusce ut nisl odio. Nullam ut pretium tortor. Aenean vel erat quam. Nulla ultrices, dolor ac mattis commodo, eros nunc sagittis tellus, et adipiscing justo purus vitae lacus. Maecenas ut augue ac risus pharetra condimentum.
Donec molestie sem ut enim ullamcorper bibendum. Curabitur in tincidunt sapien. In vestibulum iaculis augue vel scelerisque. Morbi sit amet est eget leo interdum eleifend sit amet a turpis. Mauris a leo leo. Aenean libero tellus, sagittis id laoreet et, sagittis ac lacus. Integer aliquet aliquam ultrices. Morbi urna libero, volutpat ut tempus vel, adipiscing sed mi. Mauris sit amet scelerisque ante. Maecenas quis aliquam libero. Mauris adipiscing nibh eget felis scelerisque tristique semper dolor vehicula. 
    

</div><!-- end of container_page --->
