<?=$this->headTitle()->append($this->translate('Contact form'));?>
   <div id="container_page">
    <h2><?=$this->translate('Contact form')?></h2>
<form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
    <?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->escape ( $this->error );?>
    </div>
    <?php endif;?>
<?
            
            echo $this->form->email;
            echo $this->form->message;
            echo $this->form->captcha; ?>
            <span id="agree">
            <?=$this->form->agree.$this->translate('literal_check_agree');?>
            </span>
            <? echo $this->form->submit; ?>
</form>
</div>