<div id="container_search">
    <h1>
        <a href="/" ><img  src="<?=STATIC_PATH;?>/images/foofind_search.gif" alt="File search engine - foofind.com" title="File search engine - foofind.com" /></a>
    </h1>
    <?=$this->form; ?>
    <?if ($this->qs['q']):?>
    <div class="contentype">
        <a class="<?=(preg_match("/^$/",  $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= ''.$this->qs(array(), array('type'=>1, 'page'=>1)) ?>" ><?=$this->translate('All');?></a>
        <a class="<?=(preg_match("/^Audio$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Audio'), array('page'=>1)) ?>" ><?=$this->translate('Audio');?></a>
        <a class="<?=(preg_match("/^Video$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Video'), array('page'=>1)) ?>" ><?=$this->translate('Video');?></a>
        <a class="<?=(preg_match("/^Image$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Image'), array('page'=>1)) ?>" ><?=$this->translate('Image');?></a>
        <a class="<?=(preg_match("/^Document$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Document'), array('page'=>1)) ?>" ><?=$this->translate('Document');?></a>
        <a class="<?=(preg_match("/^Software$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Software'), array('page'=>1)) ?>" ><?=$this->translate('Software');?></a>
        <a class="<?=(preg_match("/^Archive$/", $this->qs['type']))?"actual":""?>" href="/<?=$this->lang?>/search/<?= $this->qs(array('type'=>'Archive'), array('page'=>1)) ?>" ><?=$this->translate('Archive');?></a>
    </div>
    <?endif?>
    <hr />
<?
if (count ( $this->mensajes ) > 0) {
	echo '<div class="success">';
	foreach ( $this->mensajes as $msg ) {
		echo $msg . '<br>';
	}
	echo '</div>';
}
?>

    <div class="wrap_download">
    <div class="file_download">
        <div class="file_download_vote <?=$this->myvote?>"><a href="#" rel="superbox[ajax][/<?=$this->lang?>/auth/login/source/vote.foo]" type="1" class="vote_up"><div></div><?=$this->translate('I like it!')?><br/><span>(<?=$this->coalesce($this->file['votes'][$this->lang]['c'][0], 0)?>)</span></a>&nbsp;<a href="#" rel="superbox[ajax][/<?=$this->lang?>/auth/login/source/vote.foo]" type="2" class="vote_down"><div></div><?=$this->translate('Booo!')?><br/><span>(<?=$this->coalesce($this->file['votes'][$this->lang]['c'][1],0)?>)</span></a></div>
        <h2><?=$this->file['view']['fn'];?></h2>
        
        <div class="top_download">
        <div class="download_button">
            <img alt="" src="<?=STATIC_PATH;?>/images/icons/content_<?=$ctype ?>.gif" /><br />
            <a title="<?=$this->translate('Download')?>" class="superlarge magenta awesome" href="<?=$this->formatURL($this->file['view']['sources'][$this->file['view']['source']]['urls'][0])?>"><?=$this->translate('Download').((isset($this->file['file']['z']) && $this->file['file']['z']>0)?" (".$this->formatSize($this->file["file"]["z"]).')':'');?></a>
         </div>
        <div class="download_file_metadata"><? echo $this->format($this->file, true); ?></div>
       </div>

        <div class="dowload_file_sources">                
        <?
        foreach ($this->file['view']['sources'] as $src => $info)
        {
            if (isset($info['count']))
                $text = "{$info['tip']} <br/><span>({$info['count']}&nbsp;".$this->translate('Sources').")</span>";
            else
                $text = "{$info['tip']}";

            echo "<div class='download_source' >";

            foreach ($info['urls'] as $url)
            {
                $i+=1; if ($i>15) break;
                echo '<input onClick="javascript:this.focus();this.select();" type="text"  value="'.$url.'" />';
                echo "<div><img src='".STATIC_PATH."/images/icons/{$info['icon']}_download.gif'/><a title='$url' href='".$this->formatURL($url)."'>".ucfirst ( $text )."</a></div>";
            }
            echo "</div>";
        }
        ?>
        </div>

        <div class="sharelinks"><?=$this->translate('Share this:');?>
            <a href="http://www.facebook.com/share.php?u=http://foof.in/<?=$this->langcode;?>/<?=$this->file['file']['url'];?>">
                <img alt="<?=$this->translate('share on facebook');?>" src="<?=STATIC_PATH;?>/images/icons/ico_facebook.gif" border = "0"/></a>
                <a href="mailto:?subject=<?=$this->filename['Filename'];?>&body=http://foof.in/<?=$this->langcode;?>/<?=$this->file['file']['url'];?>">
                <img alt="<?=$this->translate('send by email');?>" src="<?=STATIC_PATH;?>/images/icons/ico_email_link.png" border = "0"/></a>
                <a href="http://twitter.com/home?status=http://foof.in/<?=$this->langcode;?>/<?=$this->file['file']['url'];?>">
                <img alt="<?=$this->translate('share on twitter');?>" src="<?=STATIC_PATH;?>/images/icons/ico_twitter.png" border = "0"/></a>
        </div>


       <?php
            $this->comments_refs = array();
            $this->count = count($this->file['comments']);
            $i = $this->count + 1 - ($this->paginator->getCurrentPageNumber()-1)*$this->paginator->getItemCountPerPage();
            foreach ($this->paginator as $key => $val):
                   
                $i--; ?>
        <div class="comment">
           <div class="file_comment_number"><a name="c<?=$i?>" href="?page=<?=$this->paginator->getCurrentPageNumber()?>#c<?=$i?>">#<?=$i?></a></div>
           <div class="file_comment_vote small <?=$val['myvote'] ?>" idcomment="<?=$val['_id']?>"><a href="#" rel="superbox[ajax][/<?=$this->lang?>/auth/login/source/vote.foo]" type="1" class="vote_up"><div></div><span><?=0+$val['vs']['c'][0]?></span></a>&nbsp;<a href="#" rel="superbox[ajax][/<?=$this->lang?>/auth/login/source/vote.foo]" type="2" class="vote_down"><div></div><span><?=0-$val['vs']['c'][1]?></span></a></div>
           <div id="c<?=$i?>"><?= $this->format_comment($val['t']); ?></div>
           <div class="file_comment_nick"><a href="/<?=$this->lang ?>/profile/<?=$this->escape($val['u']['username']) ?>"><?=$val['u']['username'] ?></a> - <? echo $this->show_date_span($val['d']->sec); if ($val['location']!=null) echo  " ". $this->translate("from") ." ". $val['location']; ?></div>
        </div>

        <?php endforeach;?>

        <script>
            var tooltips = [];

        <?php foreach ($this->comments_refs as $val):
                    $comment = $this->comments[$this->count-$val];
                    echo "tooltips[$val] = '<b>{$comment['u']['username']}: </b>".$this->format_comment($comment['t'])."';";
              endforeach;?>

            $('.ttlink').tooltip({
                track: true,
                delay: 0,
                showURL: false,
                bodyHandler: function() { return tooltips[$(this).attr("tooltip")]; },
                fade: 250
            });

<?php   if ($this->isAuth): ?>
            $('.file_comment_vote a').click(function(event)
            {
                event.preventDefault();
                $.ajax({dataType:"json",
                    url: "/<?=$this->lang?>/vote/comment/"+$(this).parent().attr('idcomment')+"/"+$(this).attr('type'),
                    context: $(this),
                    success: function(data){
                        parent = this.context.parent();
                        if (this.context.attr('type')=='1') {
                            parent.addClass("upactive");
                            parent.removeClass("downactive");
                        }
                        else
                        {
                            parent.addClass("downactive");
                            parent.removeClass("upactive");
                        }

                        counter = $(".vote_up span", parent).text(data['c'][0]);
                        counter = $(".vote_down span", parent).text(-data['c'][1]);
                    }
                });
            });

            $('.file_download_vote a').click(function(event)
            {
                event.preventDefault();
                $.ajax({dataType:"json",
                        url: "/<?=$this->lang?>/vote/file/<?=$this->file['file']['url']?>/"+$(this).attr('type'),
                        context: $(this),
                        success: function(data){

                            parent = this.context.parent();
                            if (this.context.attr('type')=='1') {
                                parent.addClass("upactive");
                                parent.removeClass("downactive");
                            }
                            else
                            {
                                parent.addClass("downactive");
                                parent.removeClass("upactive");
                            }

                            counter = $(".vote_up span", parent).text('('+data['<?=$this->lang?>']['c'][0]+')');
                            counter = $(".vote_down span", parent).text('('+ (-data['<?=$this->lang?>']['c'][1])+')');
                        }
                });
            });
<? else: ?>
            $(document).ready(function(){$.superbox();} );
            $.superbox.settings = {
                boxWidth: 400,
                boxHeight: 320,
                overlayOpacity: .4, // Background opaqueness
                loadTxt: "<?=$this->translate("Loading...")?>",
                closeTxt: "<?=$this->translate("Close")?>",
                prevTxt: "<?=$this->translate("Previous")?>",
                nextTxt: "<?=$this->translate("Next")?>"
            };
<?php endif;?>

        </script>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'paginator_md.phtml'); ?>
    <div class="comment_form"><?=$this->createcomment?></div>

    </div>

    <div class="download_more_info">
        <h3><?=$this->translate('How to download?'); ?></h3>
        <p><?=$this->translate('DownloadExplanation'); ?></p>
        <p><img title="eDonkey, eMule, MLDonkey, aMule" alt="eDonkey, eMule, MLDonkey, aMule"  src="<?=STATIC_PATH;?>/images/icons/ed2k.gif" /> eMule, MLDonkey, aMule.</p>
        <p><img title="Gnutella, Frostwire,Limewire, Shareaza, Phex" alt="Gnutella, Frostwire, Limewire, Shareaza, Phex"  src="<?=STATIC_PATH;?>/images/icons/gnutella.gif" /> Limewire, Shareaza, Phex.</p>
        <p><img title="Torrent, Vuze, µTorrent, Transmission" alt="Torrent, Vuze, µTorrent, Transmission"  src="<?=STATIC_PATH;?>/images/icons/torrent.gif" /> µTorrent, Transmission.</p>
    </div>

</div>
</div>
