<?=$this->headTitle()->append($this->translate('Ofertas de empleo'));?>
    <h2>Ofertas de empleo</h2>
<div class="page_text">
    <p>Si te gustan los retos, el Software Libre y los vídeos de gatitos, únete a nosotros: gente joven de espíritu,
    con ganas de aprender, equivocarse y enfrentarse a problemas técnicos poco frecuentes.
    No tenemos buffet libre como en Google, pero bajamos al bar dos veces al día.</p>
    <p>El trabajo es presencial y a jornada completa, en nuestra oficina de Madrid.</p>
    <p>Ofrecemos incorporación a un proyecto de larga duración y flexibilidad de horarios.</p>
    <div class="joboffer">
    <h2>Programador Web</h2>
    <p>Buscamos programadores con experiencia en desarrollo Web. La tarea a realizar es la de desarrollo y mantenimiento del sitio web foofind.com. Se desarrollarán funcionalidades para mejorar la experiencia del usuario, los resultados de las búsquedas, la comunidad de usuarios y el rendimiento de la aplicación.</p>
    <ul><lh>Se valorarán especialmente conocimientos y experiencia en:</lh>
    <li>PHP</li><li>Zend Framework o similar</li><li>JavaScript</li><li>AJAX</li><li>jQuery</li><li>CSS</li><li>Sphinx o similar</li><li>JSON</li><li>MySQL o similar</li><li>Entornos Linux</li></ul>
    </div>
    <div class="joboffer">
    <h2>Programador Senior</h2>
    <p>Buscamos programadores con perfil versátil, que se sientan cómodos utilizando herramientas de
        código abierto y se animen a modificarlas si hace falta. Algunas de las tareas a desempeñar son la de creación de crawlers
        para extracción de contenidos multimedia de Internet y desarrollo de extensiones para navegadores Web.</p>
    <ul><lh>Se valorarán especialmente conocimientos y experiencia en:</lh>
    <li>Python</li><li>Java</li><li>C++</li><li>MySQL o similar</li><li>Acceso a APIs de terceros</li><li>PHP</li><li>Entornos Linux</li></ul>
    </div>
    <div class="joboffer">
    <h2>Administrador de sistemas operativos Linux/FreeBSD</h2>
    <p>Buscamos una persona para desempeñar funciones de administrador de sistemas web.</p>
    <ul><lh>Se valorarán especialmente conocimientos y experiencia en administración de:</lh>
    <li>FreeBSD</li><li>Ubuntu</li><li>Apache</li><li>MongoDB</li></ul>
    <ul><lh>También se valorará:</lh>
    <li>Conocimientos de hardware.</li>
    <li>Conocimientos de programación con lenguajes de scripting, principalmente perl, php, bash (shell en general) y python.</li>
    <li>Inglés.</li>
    </ul>
    </div>
</div>
<h2>Envíanos tus datos</h2>
<form enctype="multipart/form-data" action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
    <?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->escape ( $this->error );?>
    </div>
    <?php endif;?>
<?

            echo $this->form->email;
            echo $this->form->offer;
            echo $this->form->message;
            echo $this->form->cv;
            echo $this->form->captcha; ?>
            <span id="agree">
            <?=$this->form->agree.$this->translate('literal_check_agree');?>
            </span>
            <? echo $this->form->submit; ?>
</form>