<?=$this->headTitle()->append($this->translate('Ofertas de empleo'));?>
    <h2>Ofertas de empleo</h2>
<div class="page_text">
    <p>Si te gustan los retos, el Software Libre y los vídeos de gatitos, únete a nosotros: gente joven de espíritu,
    con ganas de aprender, equivocarse y enfrentarse a problemas técnicos poco frecuentes.
    No tenemos buffet libre como en Google, pero bajamos al bar dos veces al día.</p>
    <div class="joboffer">
    <h2>Administrador de sistemas operativos Linux/FreeBSD</h2>
    <p>Buscamos una persona para desempeñar funciones de administrador de sistemas web.</p>
    <ul><lh>Se valorará especialmente conocimientos y experiencia en administración de:</lh>
    <li>CentOS</li><li>Ubuntu</li><li>FreeBSD</li><li>Apache</li><li>MongoDB</li></ul>
    <ul><lh>También se valorará:</lh>
    <li>Conocimientos de hardware.</li>
    <li>Conocimientos de programación con lenguajes de scripting, principalmente perl, php, bash (shell en general) y python.</li>
    <li>Inglés.</li>
    </ul>
    <p>Lugar de trabajo: Madrid<br/>
    Jornada: Completa</p>
    </div>
</div>
<h2>Envíanos tus datos</h2>
<form enctype="multipart/form-data" action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
    <?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->escape ( $this->error );?>
    </div>
    <?php endif;?>
<?

            echo $this->form->email;
            echo $this->form->offer;
            echo $this->form->message;
            echo $this->form->cv;
            echo $this->form->captcha; ?>
            <span id="agree">
            <?=$this->form->agree.$this->translate('literal_check_agree');?>
            </span>
            <? echo $this->form->submit; ?>
</form>