<?=$this->headTitle()->append($this->translate('Ofertas de empleo'));?>
    <h2>Ofertas de empleo</h2>
<div class="page_text">
    <p>Si te gustan los retos, el Software Libre y los vídeos de gatitos, únete a nosotros: gente joven de espíritu,
    con ganas de aprender, equivocarse y enfrentarse a problemas técnicos poco frecuentes.
    No tenemos buffet libre como en Google, pero bajamos al bar dos veces al día.</p>
    <p>El trabajo es presencial y a jornada completa, en nuestra oficina de Madrid.</p>
    <p>Ofrecemos incorporación a un proyecto de larga duración y flexibilidad de horarios.</p>
<div class="joboffer">
<h2>Programadores Python</h2>
<p>Buscamos programadores con experiencia en desarrollo con Python e interés en alguna de estas áreas:</p>
<ul>
<li>Extracción de información de contenidos multimedia de Internet.</li>
<li>Análisis, extracción y manipulación de información semántica de la web.</li>
<li>Mejora de la experiencia del usuario, los resultados de las búsquedas, la comunidad de usuarios y el rendimiento del sitio web foofind.com.</li>
</ul>
<ul><lh>Requisitos:</lh>
<li>Python</li><li>Entornos Linux</li></ul>
<ul><lh>También valoraremos conocimientos y experiencia en:</lh>
<li>JavaScript, AJAX, jQuery y JSON</li>
<li>HTML y CSS</li>
<li>Acceso a APIs de terceros</li>
<li>Flask u otros frameworks para web</li>
<li>Sphinx o similar</li>
<li>MongoDB</li></ul>
</div>
</div>
<h2>Envíanos tus datos</h2>
<form enctype="multipart/form-data" action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
    <?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->escape ( $this->error );?>
    </div>
    <?php endif;?>
<?

            echo $this->form->email;
            echo $this->form->offer;
            echo $this->form->message;
            echo $this->form->cv;
            echo $this->form->captcha; ?>
            <span id="agree">
            <?=$this->form->agree.$this->translate('literal_check_agree');?>
            </span>
            <? echo $this->form->submit; ?>
</form>
