<div id="container_search">

    <a href="/"><h1>FooFind.com</h1></a>


    
<?echo $this->form;?>

    <div class="search_info"> files found , retrieved in <?=$this->list['time']; ?> secs. </div>

 

<? //var_dump($this->paginator); ?>



<?php

//Zend_Debug::dump($this->paginator);
// die ();

if (count($this->paginator)): ?>

        <?=$this->paginationControl($this->paginator,'Sliding','paginator_search.phtml'); ?>

       <?php foreach ($this->paginator as $key => $val): ?>
        <div class="file_excerpt">

            <span><a href="/<?=$val['sources'][0]['Uri'] ?>"><?=$val['filenames'][0]['Filename'] ?></a></span>

	<ul>
            <?php foreach ($val['filenames'] as $filename): ?>
		<li><?=$filename['IdFile']?> | <?=$filename['Filename'] ?> | .<?=$filename['Extension'] ?></li>
            <?php endforeach; ?>

            <?php foreach ($val['sources'] as $source): ?>
		<li><?=$source['IdFile']?> | Type:<?=$source['Type'] ?> | Uri:<?=$source['Uri'] ?> | Sources:<?=$source['Sources'] ?></li>
	    <?php endforeach; ?>

            <?php foreach ($val['metadata'] as $md): ?>
		<li><?=$md['IdFile']?> | <?=$md['KeyMD'] ?>:<?=$md['ValueMD'] ?></li>
	    <?php endforeach; ?>
	</ul>
        </div>

        <?php endforeach; ?>

        <?=$this->paginationControl($this->paginator,'Sliding','paginator_search.phtml'); ?>
    
<?php else: ?>

    <h3><? echo 'No results. :-( ';?></h3>

<?php endif;?>


 

</div><!-- end of container_search --->
