<div id="container_user">
    <h2><?=$this->translate('Edit your profile')?></h2>
    <?php
    if (isset ( $this->error )) :
        ?>
    <div class="error">
            <?=$this->escape ( $this->error );?>
    </div>
    <?php endif;?>
    <fieldset>
            <?=$this->form;?>
        <a href="/<?=$this->lang ?>/user/delete/username/<?=$this->escape ( $this->username ); ?>" ><?=$this->translate('Delete your foofind.com account') ?></a>
    </fieldset>
</div>