<div id="container_user">

    <h2><?=$this->translate ( 'User profile' ).'  -  '.$this->user['username'];?></h2>


<?php
if (isset ( $this->error )) :
?>
<div class="error">
		<?=$this->escape ( $this->error );?>
</div>

<?php endif;?>



  <ul id="tabnav">
	<li class="tab1"><a href="/<?=$this->lang ?>/user/profile/id/<?=$this->user[IdUser] ?>"><?=$this->translate('profile');?></a></li>
	<li class="tab2"><a href="/<?=$this->lang ?>/user/edit/id/<?=$this->user[IdUser] ?>"><?=$this->translate('edit profile');?></a></li>
 </ul>



<?//=var_dump($this->user);?>
    <div class="user_profile">
        <h3><?=$this->translate('User name:').' '.$this->user['username'];?></h3>
        <h3><?=$this->translate('Member since:').' '.$this->escape(date( $this->translate('l dS \o\f F Y H:i:s'), strtotime($this->user['created'])));?></h3>
    </div>

</div>

