<?
if (count($this->mensajes) > 0) {
    echo '<div class="success">';
    $sep="";
    foreach ($this->mensajes as $msg) {
        echo $msg.$sep;
        $sep='<br/>';
    }
    echo '</div>';
}
?>
<div id="container_user">
<? if (strlen($this->message)>0): ?>
    <h2><?=$this->translate($this->message)?></h2>
<? else: ?>
    <h2><?=$this->translate('User login')?></h2>
<? endif; ?>
<p>
<?=$this->translate ( '(If you are a new user, please' );?>
&nbsp;<a href="/<?=$this->lang?>/user/register" title="user register"><?=$this->translate ( 'register here' );?></a>)
</p><?php if (isset ( $this->error )) :?>
<div class="error"><?=$this->escape ( $this->error );?></div>
<?php endif;?>
<form action="<?=$this->escape ( $this->form->getAction () )?>"
	method="<?=$this->escape ( $this->form->getMethod () )?>">

<?        echo $this->form->email;
            echo $this->form->password; ?>

            <span id="agree">
            <?=$this->form->rememberme.$this->translate('Remember me');?>
            </span>
            <? echo $this->form->submit; ?>
    <dt><a class="oauth tw" href="/<?=$this->lang?>/user/oauth/tw/login"><span><?=$this->translate('Login using');?> Twitter</span></a>
            <a class="oauth fb" href="/<?=$this->lang?>/user/oauth/fb/login"><span><?=$this->translate('Login using');?> Facebook</span></a></dt>
    <dt><a href="/<?=$this->lang ?>/user/forgot"><?=$this->translate ( 'Forgot' );?></a> <?=$this->translate ( 'your password?' );?></dt>

</form>
</div><!-- end of container_page --->
